export const ADD_INGREDIENT_CONSTRUCTOR: "ADD_INGREDIENT_CONSTRUCTOR" = 'ADD_INGREDIENT_CONSTRUCTOR';
export const DELETE_INGREDIENT_CONSTRUCTOR: "DELETE_INGREDIENT_CONSTRUCTOR" = 'DELETE_INGREDIENT_CONSTRUCTOR';
export const UPDATE_INGREDIENT_CONSTRUCTOR: "UPDATE_INGREDIENT_CONSTRUCTOR" = 'UPDATE_INGREDIENT_CONSTRUCTOR';
export const CLEAR_INGREDIENT_CONSTRUCTOR: "CLEAR_INGREDIENT_CONSTRUCTOR" = 'CLEAR_INGREDIENT_CONSTRUCTOR';
export const ADD_BUNS_CONSTRUCTOR: "ADD_BUNS_CONSTRUCTOR" = 'ADD_BUNS_CONSTRUCTOR';