export const GET_NUMBER_ORDER_REQUEST = "GET_NUMBER_ORDER_REQUEST";
export const GET_NUMBER_ORDER_SUCCESS = "GET_NUMBER_ORDER_SUCCESS";
export const GET_NUMBER_ORDER_ERROR = "GET_NUMBER_ORDER_ERROR";
