export const WS_COMMON_CONNECT = "WS_COMMON_CONNECT";
export const WS_COMMON_DISCONNECT = "WS_COMMON_DISCONNECT";
export const WS_COMMON_CONNECTING = "WS_COMMON_CONNECTING";
export const WS_COMMON_OPEN = "WS_COMMON_OPEN";
export const WS_COMMON_CLOSE = "WS_COMMON_CLOSE";
export const WS_COMMON_ERROR = "WS_COMMON_ERROR";
export const WS_COMMON_MESSAGE = "WS_COMMON_MESSAGE";
