export const WS_PROFILE_CONNECT = "WS_PROFILE_CONNECT";
export const WS_PROFILE_DISCONNECT = "WS_PROFILE_DISCONNECT";
export const WS_PROFILE_CONNECTING = "WS_PROFILE_CONNECTING";
export const WS_PROFILE_OPEN = "WS_PROFILE_OPEN";
export const WS_PROFILE_CLOSE = "WS_PROFILE_CLOSE";
export const WS_PROFILE_ERROR = "WS_PROFILE_ERROR";
export const WS_PROFILE_MESSAGE = "WS_PROFILE_MESSAGE";
