name: GitHub Actions
run-name: testing 🚀
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{matrix.node-veersion}}
      uses: actions/setup-node@v3
      with: node-version: ${{matrix.node-version}}
      - name: inistall modules
        run: npm install
      - name: build project
        run: npm run predeploy
      - name: unit test
        run: npm run test 
